### ISSUE TITLE
Leaking at Basketball Court A

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#18] opened 2017-12-14 06:28 UTC
Please check and fix leaking at court A. Please coordinate with Attendants.

Thank you.

**Comment by buildingengineers** [comment] 2018-02-09 07:44
As per initial assessment, the cause of leaking at Basketball Court A is from the storm drainage pipe that passes through the court. The storm drainage piping system has a problem regarding on its design that is why during heavy rains, the system can not drain all the storm waters resulting to some leaking on joints of the pipes that passes on the b3 court a.

**Comment by buildingengineers** [comment] 2018-04-25 15:26
Hello,

We will be closing now this issue.

Thanks,

Noel

**Closed as completed by buildingengineers** 2018-04-25 15:26 UTC
